### PR TITLE
A variant theme with navigation at the top

### PR DESCRIPTION
**Pull request by jnothman**
This is a variant theme and some helpers (in slidedefs.sty -- better name welcome) to produce a navigation bar along the top of the slides, which I find useful when trying to track timing during a presentation, as well as providing navigation to appropriate slides when asked questions. It is something my audiences also tend to appreciate, and many have asked how it's done (and I answer: not in Powerpoint/Keynote).

### CODE REVIEW

**Comment by jnothman** [comment]
PS: I understand if you're not interested in merging style variations.

**Comment by jnothman** [comment]
Much of this style and macros are due to James R Curran.  His changes should probably be credited, but seeing as he was modifying something GPL, I feel I can pass them on.

**Comment by malramsay64** [comment]
This is really cool. Thanks!

It has been a little while since I have used beamer and I would like to understand what is going on before merging. Since this allows for a choice of slides I don't have a fundamental issue with merging.

It was actually James Curran's presentations that inspired me to create this theme in the first place.  I have since preferred plainer slides, although understand why you find this style appealing.

**Comment by malramsay64** [comment]
A quick note on the general style, everything except the top and bottom bar has square corners which is consistent with the powerpoint theme. I haven't seen the theme with square bars, although I think it would improve consistency.

**Comment by jnothman** [comment]
I think plain is great for a well-rehearsed 20 min presentation, but for a
2h lecture that you've not seen in a year, the progress tracking is
wonderful :)

Ping me if I don't get back to you on squaring the circle!

**Comment by malramsay64** [comment]
I have had a chance to look through all the changes here. 

While the slide helper functions do look really useful, my opinion is they should be separate from the theme since they modify the content of the presentation.

As for the actual theme, a lot of the hacks you were using in designing the theme are mostly workarounds to the unusual way beamer handles the typesetting. Basically I was investigating the reasoning behind things and ended up re-implementing your theme in #6. I do kind of feel like it is poor form to take your work and completely rewrite it, although it is a whole lot simpler now.

I also did the squaring of the circle and other minor tweaks which results in the below slide.
screen shot 2018-06-16 at 18 06 22

I would like your input on the updated theme before I merge it.

**Pull request closed without merging**
